name: news_debater
description: 뉴스 토론 앱 - 뜨거운 이슈에 대한 여론을 확인하고 토론해보세요
publish_to: 'enigma_jun0'
version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.7

  # 보안 저장소
  flutter_secure_storage: ^9.0.0

  # 디바이스 정보
  device_info_plus: ^9.1.1
  android_id: ^0.4.0

  # 암호화
  crypto: ^3.0.3

  # HTTP 통신
  http: ^1.1.0
  dio: ^5.3.2

  # 상태 관리
  provider: ^6.0.5

  # 로컬 저장소
  shared_preferences: ^2.2.1

  # UI 컴포넌트
  fl_chart: ^0.63.0
  cached_network_image: ^3.3.0

  # 유틸리티
  intl: ^0.18.1
  uuid: ^4.0.0

  # 애니메이션
  shimmer: ^3.0.0

  # 토스트 메시지
  fluttertoast: ^8.2.2

  # URL 런처
  url_launcher: ^6.2.1

  # WebView
  webview_flutter: ^4.4.2

  # AI
  google_generative_ai: ^0.4.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Google AdMob
  google_mobile_ads: ^5.1.0

  # In-App Purchase
  in_app_purchase: ^3.1.13

  #launcher
  flutter_launcher_icons : ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true # 안드로이드 플랫폼에 런처 아이콘 적용 여부
  ios: true # iOS 플랫폼에 런처 아이콘 적용 여부
  image_path: "assets/icons/app_icon.png" # 런처 아이콘으로 사용할 이미지 경로
  adaptive_icon_background: "#000000" # 안드로이드 적응형 아이콘의 배경색 (검정색)
  adaptive_icon_foreground: "assets/icons/app_icon.png" # 안드로이드 적응형 아이콘의 전경 이미지 경로
  min_sdk_android: 21 # 안드로이드 최소 SDK 버전 (API 21(Android 5.0) 이상)

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/