name: news_debater
description: 뉴스 토론 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP 통신
  http: ^1.1.0
  dio: ^5.3.2

  # 상태 관리
  provider: ^6.0.5

  # 로컬 저장소
  shared_preferences: ^2.2.1

  # UI 컴포넌트
  fl_chart: ^0.63.0
  cached_network_image: ^3.3.0

  # 유틸리티
  intl: ^0.18.1
  uuid: ^4.1.0

  # 애니메이션
  shimmer: ^3.0.0

  # 토스트 메시지
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700